-- Phase 3a: curated data-center seed, sourced from the legacy DataSist repo
-- (aliasist/datasist server/storage.ts). Idempotent on slug.

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'amazon-web-services-aws-us-east-1-northern-virginia-ashburn',
  'AWS US-East-1 (Northern Virginia)',
  'Amazon Web Services',
  'hyperscale',
  38.9531,
  -77.3579,
  'Ashburn',
  'Virginia',
  'USA',
  450,
  3942,
  900,
  'operational',
  2006,
  NULL,
  35,
  2000,
  '["Amazon Bedrock","AWS Trainium","SageMaker"]',
  'Data Center Alley in Northern Virginia is the world''s largest concentration of data centers. Electricity prices have risen 267% over five years. 40% of Virginia''s total electricity consumption goes to data centers. A July 2024 voltage fluctuation simultaneously disconnected 60 data centers in the region.',
  1,
  'high',
  85,
  'Largest AWS region globally. Site of the July 2024 cascading grid failure that affected 60+ facilities.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'amazon-web-services-aws-us-east-2-ohio-columbus',
  'AWS US-East-2 (Ohio)',
  'Amazon Web Services',
  'hyperscale',
  39.9611,
  -82.9988,
  'Columbus',
  'Ohio',
  'USA',
  280,
  2453,
  500,
  'operational',
  2016,
  NULL,
  12,
  800,
  '["Amazon Bedrock","SageMaker"]',
  'Growing AWS presence in central Ohio. Local residents in surrounding counties have raised concerns about electricity cost increases. The Union of Concerned Scientists estimated Ohio households could see $1.2B in additional transmission costs by 2030.',
  0,
  'medium',
  72,
  'AWS expanding AI-focused infrastructure across Ohio and Indiana corridors.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'amazon-web-services-aws-us-west-2-oregon-the-dalles',
  'AWS US-West-2 (Oregon)',
  'Amazon Web Services',
  'hyperscale',
  45.5951,
  -121.2101,
  'The Dalles',
  'Oregon',
  'USA',
  200,
  1752,
  300,
  'operational',
  2011,
  NULL,
  8,
  600,
  '["SageMaker","EC2 Inf instances"]',
  'Located along the Columbia River gorge. Heavy reliance on hydropower makes this one of the greenest AWS campuses. Water use in a drought-prone area is a growing concern among local environmental groups.',
  0,
  'low',
  95,
  'Benefits from Columbia River hydropower. Model for low-carbon data center operations.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'amazon-web-services-aws-ai-supercomputing-campus-indiana-indianapolis',
  'AWS AI Supercomputing Campus (Indiana)',
  'Amazon Web Services',
  'hyperscale',
  39.7684,
  -86.1581,
  'Indianapolis',
  'Indiana',
  'USA',
  500,
  4380,
  1200,
  'under_construction',
  NULL,
  2027,
  11,
  1500,
  '["AWS Trainium2","Amazon Bedrock","U.S. Gov AI"]',
  'Part of AWS''s $50B investment to build AI and supercomputing capacity for the U.S. government. Local officials have welcomed economic investment, though environmental groups have raised concerns about water consumption and long-term grid strain.',
  0,
  'medium',
  60,
  'Part of AWS''s $50B U.S. government AI infrastructure deal.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'amazon-web-services-aws-govcloud-west-oregon-boardman',
  'AWS GovCloud West (Oregon)',
  'Amazon Web Services',
  'hyperscale',
  45.8491,
  -119.7025,
  'Boardman',
  'Oregon',
  'USA',
  160,
  1402,
  240,
  'operational',
  2014,
  NULL,
  4,
  450,
  '["AWS GovCloud","SageMaker Gov"]',
  'AWS GovCloud serves U.S. government classified workloads. The Boardman campus uses Columbia River hydropower and has established a cooperative relationship with Morrow County. Among the lowest-impact large data centers in the Pacific Northwest.',
  0,
  'low',
  97,
  'FedRAMP-authorized. Processes classified government AI workloads.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'microsoft-microsoft-azure-east-us-boydton-boydton',
  'Microsoft Azure East US (Boydton)',
  'Microsoft',
  'hyperscale',
  36.6681,
  -78.3875,
  'Boydton',
  'Virginia',
  'USA',
  260,
  2277,
  550,
  'operational',
  2012,
  NULL,
  10,
  900,
  '["Azure OpenAI","Copilot","GPT-4","DALL-E"]',
  'Mecklenburg County hosts one of Microsoft''s largest Azure campuses. Tax revenue benefits the rural county significantly. However, the facility draws more electricity than the surrounding 5 counties combined.',
  0,
  'high',
  80,
  'Powers Azure OpenAI services. Liquid-cooled NVIDIA Blackwell GPU deployments underway.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'microsoft-microsoft-ai-superfactory-wisconsin-mount-pleasant',
  'Microsoft AI Superfactory (Wisconsin)',
  'Microsoft',
  'hyperscale',
  42.7261,
  -88.112,
  'Mount Pleasant',
  'Wisconsin',
  'USA',
  300,
  2628,
  650,
  'under_construction',
  NULL,
  2026,
  3.3,
  1000,
  '["Azure OpenAI","Copilot","Microsoft 365 AI"]',
  '15 new data centers approved at a former Foxconn site. Community groups are watching closely to ensure promised local hiring materializes. Construction has brought short-term jobs but long-term employment numbers are disputed.',
  1,
  'medium',
  65,
  'Part of Microsoft''s $80B ''AI Superfactory'' network.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'microsoft-microsoft-azure-west-us-quincy-quincy',
  'Microsoft Azure West US (Quincy)',
  'Microsoft',
  'hyperscale',
  47.2343,
  -119.8526,
  'Quincy',
  'Washington',
  'USA',
  180,
  1576,
  250,
  'operational',
  2008,
  NULL,
  5,
  700,
  '["Azure AI","Bing AI"]',
  'Quincy transformed from a farming town to a major data center hub. Local tax revenue doubled. Rising electricity prices in the region have burdened residential ratepayers.',
  0,
  'medium',
  90,
  'Powered primarily by Columbia River hydropower.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'microsoft-microsoft-azure-south-central-us-san-antonio-san-antonio',
  'Microsoft Azure South Central US (San Antonio)',
  'Microsoft',
  'hyperscale',
  29.4241,
  -98.4936,
  'San Antonio',
  'Texas',
  'USA',
  140,
  1226,
  300,
  'operational',
  2015,
  NULL,
  2.5,
  400,
  '["Azure AI","Cognitive Services"]',
  'San Antonio''s data center presence has grown significantly. The ERCOT grid serves this region, which experienced widespread failures during Winter Storm Uri in 2021. Data centers competed with homes for power during the crisis.',
  0,
  'high',
  60,
  'On the ERCOT grid — high risk from Texas grid instability events.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'google-google-cloud-iowa-council-bluffs',
  'Google Cloud Iowa',
  'Google',
  'hyperscale',
  41.9028,
  -91.6322,
  'Council Bluffs',
  'Iowa',
  'USA',
  120,
  1051,
  280,
  'operational',
  2009,
  NULL,
  2.5,
  500,
  '["Gemini","Google TPU v4","Vertex AI"]',
  'Iowa''s affordable wind energy makes this campus highly efficient. Google installed closed-loop cooling systems reducing water consumption. A net positive for the local economy.',
  0,
  'low',
  100,
  'Runs on 100% renewable energy. Google''s original midwest compute hub.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'google-google-cloud-south-carolina-moncks-corner',
  'Google Cloud South Carolina',
  'Google',
  'hyperscale',
  33.7764,
  -79.1697,
  'Moncks Corner',
  'South Carolina',
  'USA',
  100,
  876,
  220,
  'operational',
  2007,
  NULL,
  1.8,
  400,
  '["Gemini","Google Search AI"]',
  'Berkeley County experienced significant economic growth. Nearby communities have raised concerns about water withdrawals from the Santee River system during drought conditions.',
  0,
  'low',
  88,
  'Among the lowest PUE scores of any US hyperscale campus.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'google-google-franklin-indiana-withdrawn-franklin',
  'Google Franklin Indiana (Withdrawn)',
  'Google',
  'hyperscale',
  39.4809,
  -86.0547,
  'Franklin',
  'Indiana',
  'USA',
  200,
  1752,
  500,
  'canceled',
  NULL,
  2026,
  0.6,
  450,
  '[]',
  'In September 2025, Google withdrew its proposal to rezone 450+ acres after intense community opposition. Residents held signs at a public meeting and loudly cheered when Google''s lawyer announced the withdrawal. Concerns centered on water usage, electricity costs, and minimal local employment benefits.',
  1,
  'medium',
  NULL,
  'Landmark case of successful community opposition — withdrawal prompted cheers from residents.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'google-google-cloud-oklahoma-city-oklahoma-city',
  'Google Cloud Oklahoma City',
  'Google',
  'hyperscale',
  35.4676,
  -97.5164,
  'Oklahoma City',
  'Oklahoma',
  'USA',
  110,
  964,
  200,
  'operational',
  2019,
  NULL,
  3,
  400,
  '["Vertex AI","Google Cloud"]',
  'Google''s Oklahoma City campus benefits from low land costs and access to wind energy from the Oklahoma panhandle. The facility has contributed $1.2B in economic activity to the state since opening. Oklahoma''s wind energy grid is among the cleanest in the nation for hyperscale operations.',
  0,
  'low',
  96,
  'One of Google''s greenest US facilities. Oklahoma wind energy powers majority of operations.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'meta-meta-ai-campus-forest-city-nc-forest-city',
  'Meta AI Campus (Forest City, NC)',
  'Meta',
  'hyperscale',
  35.3368,
  -81.8648,
  'Forest City',
  'North Carolina',
  'USA',
  180,
  1576,
  380,
  'operational',
  2012,
  NULL,
  1.5,
  600,
  '["Llama 3","Meta AI","Instagram AI"]',
  'Brought significant employment and economic investment to rural Rutherford County. Uses zero-evaporation cooling during cooler months, reducing water consumption by 80%.',
  0,
  'low',
  100,
  'One of Meta''s greenest campuses. Thermal efficiency benchmark for the industry.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'meta-meta-hyperion-louisiana-richwood',
  'Meta Hyperion (Louisiana)',
  'Meta',
  'hyperscale',
  30.1048,
  -90.4012,
  'Richwood',
  'Louisiana',
  'USA',
  5000,
  43800,
  8000,
  'under_construction',
  NULL,
  2028,
  10,
  3000,
  '["Llama 4","Meta AI next-gen"]',
  'Meta''s largest AI facility will consume at least 5 GW — three times the entire city of New Orleans. The region is already overburdened by petrochemical pollution. Environmental groups and environmental justice advocates are pushing for binding renewable commitments before construction continues.',
  1,
  'high',
  40,
  '5 GW requirement = 3× electricity of New Orleans. Most controversial AI data center in the US.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'meta-meta-ai-campus-lebanon-indiana-lebanon',
  'Meta AI Campus (Lebanon, Indiana)',
  'Meta',
  'hyperscale',
  40.0481,
  -86.4689,
  'Lebanon',
  'Indiana',
  'USA',
  1000,
  8760,
  2000,
  'under_construction',
  NULL,
  2026,
  10,
  2500,
  '["Llama 3","Meta AI"]',
  'A $10B investment bringing thousands of construction jobs. Environmental groups are monitoring water use from local aquifers. The project is projected to increase local property values but may raise electricity rates for surrounding counties.',
  0,
  'medium',
  70,
  'Meta''s largest US AI infrastructure expansion.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'meta-meta-data-center-clarksville-tn-clarksville',
  'Meta Data Center (Clarksville, TN)',
  'Meta',
  'hyperscale',
  36.5298,
  -87.3595,
  'Clarksville',
  'Tennessee',
  'USA',
  200,
  1752,
  350,
  'operational',
  2021,
  NULL,
  0.8,
  650,
  '["Meta AI","WhatsApp AI"]',
  'Meta''s Clarksville campus has been a significant employer in Montgomery County. The facility runs on 100% renewable energy through TVA''s Green Invest program. Local community groups have praised Meta''s transparency compared to other hyperscalers.',
  0,
  'low',
  100,
  'Powered by TVA renewable energy contracts. Community relations rated positive.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'xai-xai-colossus-memphis-memphis',
  'xAI Colossus Memphis',
  'xAI',
  'neocloud',
  35.1495,
  -90.049,
  'Memphis',
  'Tennessee',
  'USA',
  150,
  1314,
  200,
  'operational',
  2024,
  NULL,
  5,
  200,
  '["Grok","Grok-2","Grok-3"]',
  'Powers Grok entirely on portable methane gas turbines — bypassing the grid. Operates in a community already overburdened by industrial air pollution. Environmental advocates and local residents have filed complaints about emissions. Memphis has some of the worst air quality in Tennessee.',
  1,
  'low',
  0,
  'Powered 100% by methane gas turbines. Zero grid connection. Major controversy over pollution.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'openai-microsoft-softbank-stargate-ai-campus-texas-abilene',
  'Stargate AI Campus (Texas)',
  'OpenAI / Microsoft / SoftBank',
  'hyperscale',
  32.4487,
  -99.7331,
  'Abilene',
  'Texas',
  'USA',
  800,
  7008,
  1500,
  'under_construction',
  NULL,
  2026,
  100,
  1200,
  '["GPT-5","GPT-6","o3","Sora"]',
  'The $500B Stargate initiative''s first campus. West Texas ERCOT grid is already stressed from extreme heat events and past winter failures. Local officials have welcomed economic investment but grid reliability experts warn of cascading risk. Water rights in drought-prone West Texas are a major concern.',
  1,
  'high',
  55,
  'Flagship of the $500B Stargate initiative. GPT-5+ training operations.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'hut-8-anthropic-hut-8-river-bend-campus-louisiana-baton-rouge',
  'Hut 8 River Bend Campus (Louisiana)',
  'Hut 8 / Anthropic',
  'neocloud',
  30.4515,
  -91.1871,
  'Baton Rouge',
  'Louisiana',
  'USA',
  400,
  3504,
  700,
  'under_construction',
  NULL,
  2027,
  7,
  500,
  '["Claude 3","Claude 4","Claude Sonnet"]',
  'Hut 8 signed a 15-year, $7B lease with Fluidstack to host Anthropic''s Claude models. The site is in a region with existing environmental burden from petrochemical industry. Community organizations are pushing for binding renewable energy commitments.',
  0,
  'medium',
  50,
  'Will host Anthropic''s Claude models.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'equinix-equinix-dc-campus-ashburn-ashburn',
  'Equinix DC Campus (Ashburn)',
  'Equinix',
  'colocation',
  39.0437,
  -77.4875,
  'Ashburn',
  'Virginia',
  'USA',
  320,
  2803,
  600,
  'operational',
  1998,
  NULL,
  6,
  700,
  '["Multi-tenant","OpenAI","Cohere","Various LLMs"]',
  'The original anchor of Data Center Alley. Equinix hosts dozens of AI companies. Local schools receive significant property tax revenue, while residents face the nation''s highest per-capita data center electricity load.',
  0,
  'high',
  75,
  'World''s largest internet exchange point. Foundation of Northern Virginia''s data center ecosystem.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'equinix-equinix-ny-campus-new-york-secaucus',
  'Equinix NY Campus (New York)',
  'Equinix',
  'colocation',
  40.8448,
  -74.0731,
  'Secaucus',
  'New Jersey',
  'USA',
  180,
  1576,
  280,
  'operational',
  2002,
  NULL,
  3,
  300,
  '["Multi-tenant","Financial AI","HFT systems"]',
  'Serves New York''s financial district with ultra-low latency connections. Critical infrastructure for AI-driven high-frequency trading. Densely populated area raises concerns about heat island effect and emergency backup diesel generator emissions.',
  0,
  'medium',
  65,
  'Critical infrastructure for Wall Street AI and financial services.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'databank-databank-oklahoma-city-oklahoma-city',
  'DataBank Oklahoma City',
  'DataBank',
  'colocation',
  35.4676,
  -97.5164,
  'Oklahoma City',
  'Oklahoma',
  'USA',
  45,
  394,
  80,
  'operational',
  2018,
  NULL,
  0.3,
  80,
  '["Multi-tenant cloud","Regional enterprise AI"]',
  'DataBank OKC serves regional enterprises and state government agencies. Oklahoma''s affordable electricity rates (among the lowest in the nation) attract data center investment. The facility employs over 50 local data center technicians.',
  0,
  'low',
  70,
  'Oklahoma ranks among the cheapest states for electricity — strong incentive for data center growth.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'aligned-aligned-data-centers-tulsa-tulsa',
  'Aligned Data Centers (Tulsa)',
  'Aligned',
  'hyperscale',
  36.154,
  -95.9928,
  'Tulsa',
  'Oklahoma',
  'USA',
  60,
  526,
  90,
  'under_construction',
  NULL,
  2026,
  0.5,
  120,
  '["Enterprise AI","Edge compute"]',
  'Tulsa''s growing tech sector has attracted hyperscale-tier investment. The facility will bring approximately 200 construction jobs and 40 permanent positions to Tulsa County. Oklahoma''s renewable energy corridor runs through this region, providing access to wind power.',
  0,
  'low',
  75,
  'Part of Oklahoma''s emerging status as a secondary data center market due to low power costs.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'coreweave-coreweave-gpu-cluster-new-jersey-weehawken',
  'CoreWeave GPU Cluster (New Jersey)',
  'CoreWeave',
  'neocloud',
  40.7589,
  -74.0447,
  'Weehawken',
  'New Jersey',
  'USA',
  100,
  876,
  150,
  'operational',
  2022,
  NULL,
  1.5,
  150,
  '["GPT-4 inference","Stable Diffusion","NVIDIA H100"]',
  'CoreWeave''s NJ cluster is purpose-built for GPU-dense AI workloads. The facility serves dozens of AI startups unable to access hyperscale capacity. Power density is 5-10× traditional data centers, creating localized grid stress in the utility district.',
  0,
  'medium',
  55,
  'One of the highest GPU density facilities in the US. Primary partner for AI startups.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'google-google-data-center-fredericia-denmark-fredericia',
  'Google Data Center (Fredericia, Denmark)',
  'Google',
  'hyperscale',
  55.5661,
  9.7536,
  'Fredericia',
  'Jutland',
  'Denmark',
  90,
  788,
  150,
  'operational',
  2020,
  NULL,
  0.6,
  200,
  '["Gemini","Google Translate AI"]',
  'Uses excess heat to warm 11,000 homes in Fredericia through the city''s district heating system. A globally cited example of beneficial data center community integration. The facility is considered a model for circular economy data center design.',
  0,
  'low',
  100,
  'Waste heat warms 11,000 homes. Global model for circular economy data center design.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'microsoft-microsoft-dublin-data-center-dublin',
  'Microsoft Dublin Data Center',
  'Microsoft',
  'hyperscale',
  53.3498,
  -6.2603,
  'Dublin',
  'Leinster',
  'Ireland',
  80,
  701,
  120,
  'operational',
  2009,
  NULL,
  1.2,
  180,
  '["Azure AI","Copilot EU"]',
  'Ireland''s grid is nearly at capacity due to data center concentration. Data centers consume 21% of Irish electricity. Microsoft and others have been forced to use polluting off-grid diesel generators during peak demand. Dublin''s housing crisis has been partially attributed to data center competition for land.',
  1,
  'high',
  60,
  'Ireland''s grid maxed out. 21% of Irish electricity goes to data centers. Diesel generators used during grid stress.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'meta-meta-data-center-odense-denmark-odense',
  'Meta Data Center (Odense, Denmark)',
  'Meta',
  'hyperscale',
  55.3959,
  10.3683,
  'Odense',
  'Funen',
  'Denmark',
  120,
  1051,
  180,
  'operational',
  2020,
  NULL,
  0.8,
  250,
  '["Llama 3 EU","Meta AI Europe"]',
  'Meta''s Odense facility runs on 100% wind energy and exports waste heat to the city district heating network — warming over 6,000 homes. Considered Meta''s most environmentally responsible facility globally. Local government praised the project as a model for future data center development.',
  0,
  'low',
  100,
  'Exports waste heat to warm 6,000+ homes. Meta''s most sustainable facility.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'amazon-web-services-aws-frankfurt-region-germany-frankfurt',
  'AWS Frankfurt Region (Germany)',
  'Amazon Web Services',
  'hyperscale',
  50.1109,
  8.6821,
  'Frankfurt',
  'Hesse',
  'Germany',
  150,
  1314,
  230,
  'operational',
  2014,
  NULL,
  2.5,
  350,
  '["Amazon Bedrock EU","SageMaker EU"]',
  'Frankfurt''s data center cluster is second only to Northern Virginia globally. High land costs and strict EU regulations have slowed expansion. GDPR compliance requirements make this campus essential for European AI operations. Local energy cooperative protests have targeted high consumption.',
  1,
  'medium',
  78,
  'Europe''s largest cloud region. GDPR-compliant EU AI data residency.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'microsoft-microsoft-azure-netherlands-amsterdam',
  'Microsoft Azure Netherlands',
  'Microsoft',
  'hyperscale',
  52.3676,
  4.9041,
  'Amsterdam',
  'North Holland',
  'Netherlands',
  110,
  964,
  160,
  'operational',
  2016,
  NULL,
  1.8,
  280,
  '["Azure OpenAI EU","Copilot Europe"]',
  'The Amsterdam Internet Exchange (AMS-IX) makes the Netherlands a critical AI infrastructure hub. Dutch authorities have placed moratoriums on new data center construction in the Amsterdam area due to grid strain and land scarcity. Existing facilities are under pressure to demonstrate sustainability.',
  1,
  'high',
  82,
  'Dutch moratorium on new data centers in Amsterdam. Existing facilities face strict renewable mandates.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'google-google-deepmind-london-london',
  'Google DeepMind London',
  'Google',
  'hyperscale',
  51.5074,
  -0.1278,
  'London',
  'England',
  'United Kingdom',
  60,
  526,
  80,
  'operational',
  2018,
  NULL,
  1,
  100,
  '["Gemini Ultra","AlphaFold","DeepMind AI"]',
  'Google''s London AI hub houses DeepMind research compute. High land costs limit physical expansion. The UK''s AI Safety Institute partnerships mean this facility plays a unique role in AI governance research. UK electricity is increasingly renewable, reducing the facility''s carbon footprint.',
  0,
  'low',
  85,
  'Houses DeepMind research compute. Connected to UK AI Safety Institute.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'microsoft-microsoft-azure-japan-east-tokyo-tokyo',
  'Microsoft Azure Japan East (Tokyo)',
  'Microsoft',
  'hyperscale',
  35.6762,
  139.6503,
  'Tokyo',
  'Kanto',
  'Japan',
  100,
  876,
  160,
  'operational',
  2014,
  NULL,
  2.9,
  200,
  '["Azure OpenAI Japan","Copilot JP"]',
  'Japan''s data center market is the largest in Asia-Pacific. Tokyo facilities face extreme land scarcity and premium electricity costs. Japan''s 2024 AI infrastructure push has incentivized rapid expansion. Earthquake risk requires extensive redundancy engineering, adding to costs and community land-use concerns.',
  0,
  'medium',
  55,
  'Japan government AI push: ¥2T invested in domestic AI infrastructure. Earthquake redundancy required.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'google-google-cloud-singapore-jurong-west',
  'Google Cloud Singapore',
  'Google',
  'hyperscale',
  1.3521,
  103.8198,
  'Jurong West',
  'West Region',
  'Singapore',
  130,
  1139,
  210,
  'operational',
  2013,
  NULL,
  2,
  280,
  '["Gemini APAC","Vertex AI APAC"]',
  'Singapore hosts most major cloud providers for Southeast Asia. The government imposed a three-year moratorium on new data centers from 2019-2022 due to electricity grid strain. Singapore generates nearly all electricity from natural gas — no significant renewable capacity — making these among the highest-carbon major data centers globally.',
  1,
  'medium',
  10,
  'Singapore moratorium history. Nearly all electricity from natural gas — among highest-carbon major data centers.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'amazon-web-services-aws-seoul-region-south-korea-seoul',
  'AWS Seoul Region (South Korea)',
  'Amazon Web Services',
  'hyperscale',
  37.5665,
  126.978,
  'Seoul',
  'Seoul Capital Area',
  'South Korea',
  90,
  788,
  140,
  'operational',
  2016,
  NULL,
  1.5,
  180,
  '["Amazon Bedrock APAC","SageMaker Korea"]',
  'South Korea''s semiconductor industry makes it a natural AI infrastructure hub. Samsung and SK Hynix proximity enables tight supply chain integration. Korean government AI National Strategy includes $7B in data center incentives. High electricity costs are a challenge — South Korea relies heavily on nuclear and LNG.',
  0,
  'low',
  35,
  'Proximity to Samsung/SK Hynix semiconductor fabs. Korean government AI incentives.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'meta-meta-data-center-singapore-tuas',
  'Meta Data Center (Singapore)',
  'Meta',
  'hyperscale',
  1.2966,
  103.7764,
  'Tuas',
  'West Region',
  'Singapore',
  170,
  1489,
  260,
  'operational',
  2022,
  NULL,
  1.4,
  300,
  '["Llama 3 APAC","Meta AI SE Asia"]',
  'Meta''s Singapore campus operates in one of the world''s most land-constrained markets. The facility faces Singapore''s strict sustainability reporting requirements but struggles with the city-state''s lack of renewable energy. Meta has committed to purchasing renewable energy certificates from regional solar projects.',
  0,
  'medium',
  20,
  'One of Meta''s largest APAC facilities. Limited by Singapore''s renewable energy constraints.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'microsoft-microsoft-azure-sydney-sydney',
  'Microsoft Azure Sydney',
  'Microsoft',
  'hyperscale',
  -33.8688,
  151.2093,
  'Sydney',
  'New South Wales',
  'Australia',
  75,
  657,
  120,
  'operational',
  2014,
  NULL,
  1,
  160,
  '["Azure AI ANZ","Copilot Australia"]',
  'Australia''s data center market is growing rapidly driven by government cloud mandates. Sydney facilities face water stress concerns given Australia''s drought cycles. Microsoft has committed to water-positive operations in Australia by 2030, investing in local watershed restoration projects.',
  0,
  'low',
  70,
  'Australian government cloud mandates driving rapid growth. Water-positive commitment by 2030.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'microsoft-microsoft-azure-uae-north-dubai-dubai',
  'Microsoft Azure UAE North (Dubai)',
  'Microsoft',
  'hyperscale',
  25.2048,
  55.2708,
  'Dubai',
  'Dubai',
  'UAE',
  85,
  745,
  280,
  'operational',
  2019,
  NULL,
  1.5,
  190,
  '["Azure AI UAE","Copilot Arabic"]',
  'UAE''s AI ambitions (''UAE Strategy for Artificial Intelligence 2031'') have driven massive data center investment. The desert climate creates extraordinary cooling challenges — facilities use 3-4× more water per MW than temperate locations. Water scarcity in the region makes this a critical environmental concern.',
  0,
  'medium',
  25,
  'Desert cooling requires 3-4× more water per MW. UAE AI Strategy 2031 is driving expansion.'
);

INSERT OR IGNORE INTO data_centers (
  slug, name, company, company_type, lat, lng, city, state, country,
  capacity_mw, estimated_annual_gwh, water_usage_million_gallons, status,
  year_opened, year_planned, investment_billions, acreage,
  primary_models, community_impact, community_resistance, grid_risk,
  renewable_percent, notes
) VALUES (
  'amazon-web-services-aws-riyadh-region-saudi-arabia-riyadh',
  'AWS Riyadh Region (Saudi Arabia)',
  'Amazon Web Services',
  'hyperscale',
  24.7136,
  46.6753,
  'Riyadh',
  'Riyadh Province',
  'Saudi Arabia',
  120,
  1051,
  400,
  'operational',
  2023,
  NULL,
  5.3,
  300,
  '["Amazon Bedrock ME","SageMaker Arabic"]',
  'Saudi Arabia''s Vision 2030 tech transformation drives $5.3B investment. The facility runs almost entirely on fossil fuels — Saudi Arabia has minimal renewable capacity in place. Extreme summer temperatures (50°C+) require massive mechanical cooling, creating one of the highest PUE scores of any major cloud region globally.',
  0,
  'medium',
  8,
  'Part of Saudi Vision 2030. Extreme heat requires massive cooling — among highest PUE globally.'
);

